# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  version: "0.1.0"

package:
  name: "pyre"
  version: 0.1.0

source:
  - path: ../pyre
  - path: ../LICENSE

build:
  script:
    - mkdir -p ${PREFIX}/lib/mojo
    - magic run mojo package . -o ${PREFIX}/lib/mojo/pyre.mojopkg

requirements:
  run:
    - max >=24.6.0

about:
  homepage: https://github.com/saviorand/pyre
  license: MIT
  license_file: LICENSE
  summary:  Networking abstractions for Mojo 
  repository: https://github.com/saviorand/pyre
