name: Release tag pipeline

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    uses: ./.github/workflows/test.yml
  
  package:
    uses: ./.github/workflows/package.yml
  
  publish:
    uses: ./.github/workflows/publish.yml
    secrets:
      PREFIX_API_KEY: ${{ secrets.PREFIX_API_KEY }}

  upload-to-release:
    name: Upload to release
    needs: package
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
      - uses: actions/download-artifact@v4
        with:
          name: pyre-package
      
      - name: Upload package to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: pyre.mojopkg
          tag: ${{ steps.get_version.outputs.VERSION }}
          overwrite: true
